version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - cicd-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge
